### ISSUE TITLE
How to use attribute models, gamma, top_k and discriminators?

### ISSUE THREAD

**Issue by songproducer** [uber-research/PPLM#13]
I am running run_pplm_discrim_train.py and it looks like it’ll finish its first epoch overnight. Will that result in producing a file?

I’m interested in how to use different attribute models and discriminators.

It’s a lot of fun experimenting with this software. I’m also unsure how gamma, temperature and top_k affect the text. I’d really appreciate any guidance.

**Comment by shamoons** [comment]
Any help on this?
