### ISSUE TITLE
Story generation with skeleton?

### ISSUE THREAD

**Issue by strwberry-smggls** [uber-research/PPLM#14]
Hi there!

This is quite an interesting project and I've been experimenting a lot with different setups, generating theater plays and other more unconventional pieces of text.
I have a question about the small story-writing part of the paper. The results looked very interesting and I wanted to try it on my own.
Basically, what kind of input do you give to the language model when you "fill in the blanks" between the story skeleton? Do you generate text then feed the skeleton piece, then generate text again ect. or did you come up with a different approach?

Best wishes,
Lukas

**Comment by dathath** [comment]
Hello Lukas,

Sorry for the delay in responding. We did the former i.e,  "generate text then feed the skeleton piece, then generate text again", and the story skeleton is from [here](http://improvencyclopedia.org/games/Story_Spine.html).
