### ISSUE TITLE
Perplexity evaluation 

### ISSUE THREAD

**Issue by ishikasingh** [uber-research/PPLM#16]
Did you also released the method/script used for evaluating perplexity?

**Comment by dathath** [comment]
We used the GPT model (not GPT-2) that is provided by the hugging-face interface. This should be a useful reference: https://huggingface.co/transformers/model_doc/gpt.html

**Comment by dathath** [comment]
https://github.com/huggingface/transformers/issues/473 This might be useful. Closing this issue for now, feel free to reopen if needed.
