### ISSUE TITLE
Equation (5) in your paper

### ISSUE THREAD

**Issue by pgrandinetti** [uber-research/PPLM#2]
Trying to understand how you compute the right-hand side of (5) in your paper here https://arxiv.org/pdf/1912.02164.pdf

1. For each word `w_i` in the bag-of-words 
  a. Compute Prob. that `w_i` is the next word in the sentence, given the unconditioned model `p(x)`.
2. Sum all probabilities got in step 1 (one such probability for every word in the BoW)
3. Compute log of what you got at step 2
4. Assume that's equal to `p(a|x)`

Point 1.a is mainly what I'd like to check, as I am not familiar with you notation `p_{t+1} [w_i]` (in particular, the squared brackets).

Can you kindly confirm/correct? Thanks!

Incidentally, is this where you do (implicitly) that computation? https://github.com/uber-research/PPLM/blob/master/run_pplm.py#L211

**Comment by dathath** [comment]
Yes! Your interpretation is correct. We will elaborate to clarify that when we update the paper.

Also, the pointer to the code is also correct. 

Thanks!
