### ISSUE TITLE
paper_code usage of scripts

### ISSUE THREAD

**Issue by akhileshgotmare** [uber-research/PPLM#25]
Hi @dathath @w4nderlust ! 

I'm facing issues in replicating results with scripts in the `paper_code` folder.
Could you share the usage/bash script to run pplm with the pretrained ckpts (atleast for sentiment and detoxification)?
Would be really helpful if the scripts to train pplm for sentiment and detoxification with `paper_code` are also available.

Specifically I'm stuck with (1) this import `from run_gpt2 import top_k_logits` here - 
https://github.com/uber-research/PPLM/blob/master/paper_code/gpt2tunediscrim.py#L24

and (2) this drive link https://github.com/uber-research/PPLM/blob/master/paper_code/setup_script.sh#L6
doesn't seem to work
`./gdown.pl https://drive.google.com/open?id=15TvAxA8TS8nn1lCzpVPn-Myp5RDlJiHF gpt2`.

Thanks!

**Comment by dathath** [comment]
Hi Akhilesh,
(2) is just the standard gpt-2 weights (which you can get from the openai repo, or hugging-face). I emptied the drive a while ago, I will update the instructions to reflect this soon.

For (1), I will investigate the missing imports (likely after this weekend's ICLR deadline). Meanwhile, we also share the pre-trained discriminator models in the repository.

**Comment by dathath** [comment]
I have added run_gpt2.py -- can you confirm if you are able to run training?
