### ISSUE TITLE
Results always deterministic. 

### ISSUE THREAD

**Issue by lisenkaci** [uber-research/PPLM#9]
whenever I run the model with the same cond_text the output result is always the same. I have tried changing the temperature, and top_k but still I can't get the model to return different results. How do I make it more indeterministic?

**Comment by lisenkaci** [comment]
One solution I just figured out  is to provide a random seed int when I run the model (i.e. --seed 900). Each seed returns the same result for the specific cond_text though.  I would have to randomly generate a seed every-time, which is fine but I was wondering if there is another solution?

**Comment by dathath** [comment]
The default for sample was set to False -- which meant topk=1 was always being used, I have updated it to True.  Also, you can now change the random seed to get a different sample.

Are you using the --sample flag?

Sorry, just read the new comment.

**Comment by dathath** [comment]
You can also use the --num-samples flag and query more samples. Each one will automatically be generated from a different random seed, but running this command repeatedly will give you the same batch of samples.
